### ISSUE TITLE
Support for loading from pretrained checkpoint when enable ZERO-3

### ISSUE THREAD

**Issue by ZiyueHuang** [comaniac/epoi#4]
Thanks for the excellent project. It is particularly useful when one wants to finetune from a pretrained LLM (only minimal change from the original scripts is required).

`AutoModelForCausalLM.from_pretrained` under `InjectModuleContext` gives warnings "Some weights of the model checkpoint at gpt2-medium were not used when initializing GPT2LMHeadModel ...", because the names of some parameters from the injected module has changed.

I think we can override the `_load_from_state_dict` of the injected module to fix this issue. See [_load_state_dict_into_model](https://github.com/huggingface/transformers/blob/66ded238cd04e29ba98485984dd647e7d37d1603/src/transformers/modeling_utils.py#L494) which is called from [_load_pretrained_model](https://github.com/huggingface/transformers/blob/66ded238cd04e29ba98485984dd647e7d37d1603/src/transformers/modeling_utils.py#L2975) in HF.

**Comment by comaniac** [comment]
Thanks for your interest to this project and what you have proposed sounds a good idea. Would you be able to submit a PR for it?

**Comment by ZiyueHuang** [comment]
Sure. I'd be happy to contribute this feature.
